plugin: gcp_compute

projects:
  - "prefab-poetry-334607"

regions:
  - "europe-north1"

# it works, but now is broken. Later I'll fix it
# hostnames:
#   - name

filters:
   - "labels.service_name = registry"

groups:
  group_registry: "'registry' in labels['service_name']"

auth_kind: serviceaccount

service_account_file: ../credentials/.gcp-creds.json
